# Generated by Django 6.0.5 on 2026-05-06 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='link',
            field=models.CharField(blank=True, help_text='URL для перехода', max_length=200),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='notif_type',
            field=models.CharField(choices=[('info', 'ℹ️ Инфо'), ('event', '📅 Событие'), ('absence', '📋 Отсутствие'), ('ticket', '🆘 Тикет')], default='info', max_length=10),
        ),
    ]
