# Generated by Django 6.0.5 on 2026-05-06 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendarevent_shared_with_inappnotification_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencerecord',
            options={'ordering': ['-start_dt'], 'verbose_name': 'Запись об отсутствии', 'verbose_name_plural': 'Записи об отсутствии'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оповещение', 'verbose_name_plural': 'Оповещения'},
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['start_dt'], 'verbose_name': 'Событие календаря', 'verbose_name_plural': 'События календаря'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='inappnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка в IT', 'verbose_name_plural': 'Заявки в IT'},
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Новая'), ('in_progress', '🔧 В работе'), ('resolved', '✅ Решена'), ('closed', '📁 Закрыта')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='custom_reason',
            field=models.CharField(blank=True, max_length=150, verbose_name='Другая причина (текст)'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='end_dt',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='reason',
            field=models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Болезнь'), ('other', 'Другая причина')], max_length=10, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='start_dt',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='department',
            field=models.CharField(blank=True, choices=[('emias', 'ЕМИАС'), ('parus', 'ПАРУС'), ('pacs', 'ПАКС'), ('lis', 'ЛИС'), ('it_dev', 'Отдел разработки'), ('other', 'Прочее')], max_length=10, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='scope',
            field=models.CharField(choices=[('all', 'Весь отдел'), ('dept', 'Подразделение')], default='all', max_length=10, verbose_name='Область рассылки'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(verbose_name='Текст оповещения'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='notify_before',
            field=models.DurationField(blank=True, help_text='Например: 1 day', null=True, verbose_name='Напоминать за'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_events', to=settings.AUTH_USER_MODEL, verbose_name='Поделиться с'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_dt',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название события'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('private', 'Только я'), ('dept', 'Подразделение'), ('all', 'Весь отдел')], default='private', max_length=10, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('emias', 'ЕМИАС'), ('parus', 'ПАРУС'), ('pacs', 'ПАКС'), ('lis', 'ЛИС'), ('it_dev', 'Отдел разработки'), ('other', 'Прочее')], default='other', max_length=10, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_external',
            field=models.CharField(blank=True, max_length=20, verbose_name='Внешний телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Внутренний телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('adm', 'Администратор'), ('sup', 'Начальник'), ('sid', 'Руководитель подразделения'), ('usr', 'Сотрудник')], default='usr', max_length=3, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='link',
            field=models.CharField(blank=True, help_text='URL для перехода', max_length=200, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='notif_type',
            field=models.CharField(choices=[('info', 'ℹ️ Инфо'), ('event', '📅 Событие'), ('absence', '📋 Отсутствие'), ('ticket', '🆘 Тикет')], default='info', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.supportticket', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Ответ на заявку',
                'verbose_name_plural': 'Ответы на заявки',
                'ordering': ['created_at'],
            },
        ),
    ]
