# Generated by Django 6.0.5 on 2026-05-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_patronymic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmedaBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Памятка сотрудника', max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='brochures/', verbose_name='PDF файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Файл-памятка',
                'verbose_name_plural': 'Файлы-памятки',
            },
        ),
        migrations.CreateModel(
            name='VmedaInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок раздела')),
                ('content', models.TextField(verbose_name='Текст раздела (поддерживает переносы строк)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Раздел справки ВМедА',
                'verbose_name_plural': 'Разделы справки ВМедА',
                'ordering': ['order'],
            },
        ),
    ]
