# Generated by Django 6.0.5 on 2026-05-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_alter_announcement_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('adm', 'Администратор'), ('sup', 'Начальник'), ('sid', 'Руководитель подразделения'), ('doc_clerk', 'Делопроизводитель'), ('usr', 'Сотрудник')], default='usr', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='reports/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Рапорт',
                'verbose_name_plural': 'Рапорты',
                'ordering': ['-created_at'],
            },
        ),
    ]
