# Generated by Django 6.0.5 on 2026-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employee_role_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('adm', 'Администратор'), ('sup', 'Начальник'), ('dep', 'Заместитель начальника'), ('sid', 'Руководитель направления'), ('doc_clerk', 'Делопроизводитель'), ('usr', 'Сотрудник')], default='usr', max_length=20, verbose_name='Роль'),
        ),
    ]
