# Generated by Django 6.0.5 on 2026-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmedaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ссылки')),
                ('url', models.URLField(verbose_name='Адрес ссылки (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Описание (появится при раскрытии)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
                'ordering': ['order', 'title'],
            },
        ),
    ]
